name = "recita"
compatibility_date = "2024-09-01"

[build]
command = ""                # no build step needed
pages_build_output_dir = "public"

[[d1_databases]]
binding = "recita-users"
database_name = "recita-users"
database_id = "dc1e30d0-5b1c-469c-a8e0-250d23d703cf"
