name = "recita"
compatibility_date = "2023-12-01"

[assets]
directory = "./public"
[site]
bucket = "./public"

[[d1_databases]]
binding = "DB"
database_name = "recita-users"
database_id = "dc1e30d0-5b1c-469c-a8e0-250d23d703cf"

