name = "recita"
compatibility_date = "2023-10-01"

[[d1_databases]]
binding = "DB"
database_name = "recita-users"
database_id = "xxxx-xxxx-xxxx"  # Replace with actual ID after creating in Cloudflare
